name: auto-sign

on:
  schedule:
    - cron: '30 11 * * *' # 北京时间 7:00
  workflow_dispatch:

jobs:
  sign:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: install dependencies
        run: |
          pip install requests playwright
          playwright install firefox

      - name: run sign script
        env:
          USER_JSON: ${{ secrets.USER_JSON }}
        run: |
          python sign.py
